Update LOCALIZATION_CONTRIBUTORS
qiskit-community/qiskit-translations pull request #1018
Opened 2023-01-24 01:02 UTC by alejandro-medici

* Update LOCALIZATION_CONTRIBUTORS
* Alejandro Medici for Spanish added

2023-01-24 01:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/qiskit-community/qiskit-translations?pullRequest=1018) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/qiskit-community/qiskit-translations?pullRequest=1018) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/qiskit-community/qiskit-translations?pullRequest=1018) it.</sub>

2023-01-24 01:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/qiskit-community/qiskit-translations?pullRequest=1018) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/qiskit-community/qiskit-translations?pullRequest=1018) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/qiskit-community/qiskit-translations?pullRequest=1018) it.</sub>

2023-01-24 15:47 UTC, clausia commented
@alejandro-medici has successfully joined Crowdin

2023-01-24 15:53 UTC, clausia requested changes

2023-01-24 15:53 UTC, clausia commented on LOCALIZATION_CONTRIBUTORS
> +Alejandro Medici (AR)
We do not include the countries where each person is from, please check the list of the other languages, in a later commit the "`(AR)`" of the contributor that also has the country will be removed.
Please remove the parentheses indicating your country.

2023-01-25 15:23 UTC, alejandro-medici reviewed
Country removed

2023-01-25 15:38 UTC, clausia approved these changes
LGTM

2023-01-25 15:40 UTC, merged