Update LOCALIZATION_CONTRIBUTORS
qiskit-community/qiskit-translations pull request #780
Opened 2021-12-02 14:38 UTC by 4nj4n3y4n-learner

### Summary

Related #<replace_me_with_related_issue_number>

2021-12-02 14:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/qiskit-community/qiskit-translations?pullRequest=780) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/qiskit-community/qiskit-translations?pullRequest=780) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/qiskit-community/qiskit-translations?pullRequest=780) it.</sub>

2022-01-30 07:00 UTC, AnsahMohammad approved these changes

2022-02-02 01:56 UTC, SooluThomas requested changes
@AnsahMohammad -- Did @4nj4n3y4n-learner send a join request in Crowdin?

2022-02-02 13:53 UTC, AnsahMohammad commented
@SooluThomas -- NO, [@4nj4n3y4n](https://github.com/4nj4n3y4n-learner) hasn't sent a request on crowdin yet, I've sent him the relevant links and information.

2022-02-02 18:05 UTC, SooluThomas commented
Hi @4nj4n3y4n-learner , please [do step 4 and 5 in the instructions](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations) to join the translations in Crowdin. Thank you

2022-02-04 15:54 UTC, SooluThomas approved these changes

2022-02-04 15:54 UTC, merged